---
title: 'Data Handling: Import, Cleaning and Visualisation'
author: "Aurélien Sallin (lecturer) and Andrea Burro (class tutor)"
date: "20/11/2025"
output:
  pdf_document: default
  html_document:
    highlight: tango
    mathjax: http://example.com/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    theme: cerulean
header-includes:
- \usepackage[T1]{fontenc}
- \usepackage{hyperref}
css: ../../style/notes.css
subtitle: 'Exercise 4: Data Import and Data Preparation/Manipulation'
bibliography: ../../references/datahandling.bib
---


```{r set-options, echo=FALSE, cache=FALSE, purl=FALSE, message=FALSE, warning=FALSE}
options(width = 100)
library(knitr)
library(bookdown)
library(tidyverse)
```


## Exercise A
Read Section 11.-11.4 in https://r4ds.had.co.nz/data-import.html and solve the problem posed in Section 11.4.2 ("Problems") by going step-by-step through the instructions. Hint: You will need to have the `readr` package installed and loaded (should be also installed/loaded with `tidyverse`).


## Exercise B
1. Download the file `airquality_data.xlsx` posted on Canvas and save it in your `r_course/data` folder.
2. The file is a dataset that contains the New York air quality measurements. Familiarize with the data using `print`. Do you think the dataset has problems? (Hint: look at the `type` of each column).
3. Fix the problem identified in point 2. Save the new dataset as airquality_data_fixed.xlsx using `write_xlsx` from `tidyverse/writexl`.
4. Write your solution down in an R-Script and document in this script why certain problems occur and how you solved them (using comments).


## Exercise C
1. Visit the EU Open Data Portal on COVID cases.
2. Download the "COVID-19 Cases Worldwide" data in JSON format. However, do not download these data manually (i.e., do not click-and-save). Instead, load the data directly into RStudio from the web. Hint 1: consider the `jsonlite` package. Hint2: the direct link to the JSON file (https://opendata.ecdc.europa.eu/covid19/casedistribution/json/) may be helpful.
3. Reformat the JSON data that you have imported into RStudio to a rectangular format (such that each record is represented as a row and each field as a column).