---
title: 'Data Handling: Import, Cleaning and Visualisation'
author: "Dr. Aurélien Sallin"
subtitle: 'Lecture 5:<br>Updates on exam and group project'
date: "2025-10-24"
echo: false
code-line-numbers: false
format:
  revealjs:
    template-partials:
       - ../../style/title-slide.html
    width: 1280
    height: 720
    smaller: true
    embed-resources: true
    self-contained: true
    slide-number: c
    theme: ../../style/hsgtheme.scss
highlight-style: dracula 
cache: false
---

## Exam expectations

  - The *mock exam* is online 💣.
  - The central exam is exactly like the mock exam and like the quizzes.
  - If you attend the course, and do the quizzes regularly, you'll get familiar to the way I like asking questions...
  - Goal: you understand the concepts seen in the course and you can read and understand code.
  - **You are not asked to write code.** 


## Exam expectations

  - True/False questions, multiple-choice questions, and multiple-correct options. These are designed to test your understanding of the material.
  - ❗Exactly same style  and structure as quizzes and mock exam❗
  - We do not invent wrong function parameters or misspell function names etc to mislead you!
  - 'Passive' knowledge of key R syntax and most important functions of core lecture contents are important!

<br>

  - Work step-by-step through the code example. What happens in each parenthesis, on each line? 
  - From the inner part to the outer part, from top to bottom.
  - Use pencil/paper to keep track of values, data structures (how does a data-frame look like?), classes.
  - Importantly, if a code-example question refers to specific functions, you can always assume that the corresponding package is also loaded.



## The project is online

  - have fun
  - first contact with R 
  - use API like a pro
  - create a report in R
  - use LLMs to help you solve it
  - split tasks within the group
  
  - only questions asked on the forum in Canvas will be answered
  - deadline: November 6th, 2025, 23:59