---
title: 'Data Handling: Import, Cleaning and Visualisation'
author: "Aurélien Sallin (lecturer) and Andrea Burro (class tutor)"
output:
  pdf_document: default
  word_document: default
  html_document:
    highlight: tango
    mathjax: http://example.com/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    theme: cerulean
header-includes:
- \usepackage[T1]{fontenc}
- \usepackage{hyperref}
css: ../../style/notes_hsg.css
subtitle: 'Exercise 5: Data Reshaping, Cleaning, and Merging'
---

```{r set-options, echo=FALSE, cache=FALSE, purl=FALSE, warning=FALSE, message=FALSE}
options(width = 100)
library(knitr)
library(bookdown)
```

## Exercise A: Reshaping Data

In this exercise, we will learn how to reshape data into long format using the built-in `economics` dataset from the `ggplot2` package. Load the dataset into your R session. It contains monthly data on several indicators of the U.S. economy:

| Variable | Description                                         |
|----------|-----------------------------------------------------|
| date     | month of data collection                            |
| pce      | personal consumption expenditures (billions of USD) |
| pop      | total population (thousands)                        |
| psavert  | personal savings rate                               |
| unempmed | median duration of unemployment (weeks)             |
| unemploy | number of unemployed (thousands)                    |

### A.1 - Convert to Long Format

Reshape the dataset into long format, so that for each date, there are multiple rows — one for each of the other variables. Save the result as `df_long`.

### A.2 - Convert to Wide Format

From the new `df_long` dataset, reshape the data back to its original wide format, and save it as `df`.

## Exercise B: Cleaning Data

In this section, we'll practice three important data-cleaning functions from `dplyr`: `filter()`, `select()`, and `mutate()`.

### B.1 - Filter Observations

Start with data `df`. We are only interested in observations collected after the year 2000. Filter the data accordingly and save the result as `df_reduced`.

### B.2 - Select Observations

Now we are only interested in the evolution of `pce` and `pop` over time. Clean the data accordingly and save the new dataset `df_reduced`.

### B.3 - Create Indicator Variable

We want to add a variable that marks all observations collected after the year 2000. Create a new variable called `after_2000` and add it to `df_reduced`.

## Exercise C: Merging Data

In the final exercise, we will learn how to merge two dataframes using `left_join()` from `dplyr`.

### C.1 - Merge Datasets

We want to flag the original `economics` dataset with a new variable indicating whether each observation was collected after 2000. Use `left_join()` to merge `df` (the original dataset) with `df_reduced` (which contains after_2000). Which dataset should be used as the master (left) table, and which one as the joining (right) table?

### C.2 - Handle Missing Values

The merge created some missing values for the variable `after_2000`. Explain why this could happen, and propose a solution to have a tidy dataset.



